### ISSUE TITLE
Add Harmonic PAV

### ISSUE THREAD

**Issue by fsargent** [electionscience/Examples#28]
Add Harmonic PAV to methods.py

https://github.com/nealmcb/pr_voting_methods/blob/master/pav.py

Do we want to do it with a C extension?
https://rangevoting.org/CleanOptPRVote.c

https://docs.python.org/3/extending/extending.html

**Comment by adienes** [comment]
PAV is actually already implemented in the repo via the combination of `exhaustive_optimal` and `harmonic_utility` in `proportionality_metrics.py` it's just quite slow.

If you want to use C to speed it up, probably ctypes (https://docs.python.org/3/library/ctypes.html) would be easier than extending Python. However this will still only enable faster brute-force PAV. If we really want high-performance PAV should probably plug into some MINLP solver via JuMP, which we can do with PyJulia (https://www.juliabloggers.com/how-to-call-julia-code-from-python/)

**Comment by fsargent** [comment]
How do you combine `exhaustive_optimal` and `harmonic_utility` ?

**Comment by adienes** [comment]
```
def PAV(ballots, seats):
    return exhaustive_optimal(ballots, seats, harmonic_utility)
```

**Comment by fsargent** [comment]
Looks like that's still just returning a value, not the winner set.
![CleanShot 2022-06-14 at 16 58 00](https://user-images.githubusercontent.com/273880/173708632-13fc71a1-8ab2-43f9-87f8-0459f3bbddf8.png)
https://github.com/electionscience/examples/pull/30/files#diff-88efb534a914efb382ee238df8d25bd030268d084f589d787c4c9dae507a954eR39-R44

Any tips?

**Comment by adienes** [comment]
Oops, you're right. May as well just recreate the whole thing then. This should work I think?

```
def PAV(ballots: pd.DataFrame, seats: int):
    def H(x): sum(1 / i for i in range(1, x + 1))
    
    best_score = 0
    best_committee = None
    for wset in combinations(ballots.columns, seats):

        harmonic_score = ballots[wset].sum(axis=1).map(H).sum()
        if harmonic_score > best_score:
            best_score, best_committee = harmonic_score, wset

    return best_committee
```

**Comment by fsargent** [comment]
![CleanShot 2022-06-15 at 15 01 41](https://user-images.githubusercontent.com/273880/173939818-35e55b1e-005c-4cf3-93f2-ba26b5677058.png)

**Comment by adienes** [comment]
```
def PAV(ballots: pd.DataFrame, seats: int):
    def H(x): return sum(1 / i for i in range(1, int(x) + 1))
    
    best_score = 0
    best_committee = None
    for wset in combinations(ballots.columns, seats):

        harmonic_score = ballots[list(wset)].sum(axis=1).map(H).sum()
        if harmonic_score > best_score:
            best_score, best_committee = harmonic_score, wset

    return list(best_committee)
```

Ok, I actually tested this locally this time instead of eyeballing. This implementation works on my end but lmk if you have issues. It is still slowwwwwwww since it has to iterate (in non-vectorized python loop) over every single way to choose the possible winner set

**Comment by fsargent** [comment]
https://github.com/electionscience/examples/pull/30

**Comment by fsargent** [comment]
Looks like it's ready now.
